version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "9920:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: